-- Create the account table first since it's referenced by the user table
CREATE TABLE IF NOT EXISTS account
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance         DOUBLE PRECISION NOT NULL CHECK (balance >= 0),
    initial_deposit DOUBLE PRECISION NOT NULL
);

-- Create the user table with a foreign key reference to the account table
CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    birth_date TIMESTAMP    NOT NULL,
    login      VARCHAR(20)  NOT NULL,
    password   VARCHAR(255) NOT NULL,
    account_id BIGINT,
    CONSTRAINT fk_account
        FOREIGN KEY (account_id)
            REFERENCES account (id)
            ON DELETE SET NULL
);

-- Create the user_emails table with a foreign key reference to the user table
CREATE TABLE IF NOT EXISTS user_emails
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT       NOT NULL,
    email   VARCHAR(254) NOT NULL,
    CONSTRAINT fk_user_emails
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

-- Create the user_phones table with a foreign key reference to the user table
CREATE TABLE IF NOT EXISTS user_phones
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT      NOT NULL,
    phone   VARCHAR(20) NOT NULL,
    CONSTRAINT fk_user_phones
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);
